class HyperParameter(object):
    BATCH_SIZE = 64
    NUM_EPOCHS = 50
    LEARNING_RATE = 1e-3
    IMAGE_WIDTH = 128
    IMAGE_HEIGHT = 128
    IMAGE_CHANNEL = 3
    BUFFER_SIZE = 1000
    VAL_SUB_SPLITS = 5
